const ADD_TODOLIST = 'ADD_TODOLIST'
const EDIT_TODOLIST = 'EDIT_TODOLIST'
const DELETE_TODOLIST = 'DELETE_TODOLIST'
const COMPLETED_TODOLIST = 'COMPLETED_TODOLIST'
const SORT_TODOLIST = 'SORT_TODOLIST'

export {
    EDIT_TODOLIST,
    ADD_TODOLIST,
    DELETE_TODOLIST,
    COMPLETED_TODOLIST,
    SORT_TODOLIST
}

